# Generated by Django 5.2.17 on 2026-08-20 02:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("alunos", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="aluno",
            name="serie",
            field=models.CharField(
                choices=[
                    ("6", "6º Ano"),
                    ("7", "7º Ano"),
                    ("8", "8º Ano"),
                    ("9", "9º Ano"),
                ],
                default=1,
                max_length=10,
            ),
            preserve_default=False,
        ),
    ]
