# Generated by Django 5.2.17 on 2026-08-23 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("alunos", "0003_alter_aluno_serie"),
    ]

    operations = [
        migrations.AddField(
            model_name="aluno",
            name="xp",
            field=models.PositiveIntegerField(default=0, verbose_name="XP"),
        ),
    ]
