# Generated by Django 5.2.15 on 2026-09-09 04:34

import alunos.media
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("alunos", "0005_aluno_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="aluno",
            name="foto",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to=alunos.media.upload_foto_aluno,
                verbose_name="Foto",
            ),
        ),
        migrations.AddField(
            model_name="aluno",
            name="mostrar_foto_ranking",
            field=models.BooleanField(
                default=False,
                help_text="Somente com esta opção marcada a foto aparece no ranking público.",
                verbose_name="Mostrar foto no ranking",
            ),
        ),
    ]
