# Generated by Django 5.2.15 on 2026-09-09 05:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("alunos", "0006_midia_imagens"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Turma",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nome",
                    models.CharField(
                        help_text="Identificação da turma na série, por exemplo A ou Integral.",
                        max_length=80,
                        verbose_name="Nome",
                    ),
                ),
                (
                    "serie",
                    models.CharField(
                        choices=[
                            ("5", "5º Ano"),
                            ("6", "6º Ano"),
                            ("7", "7º Ano"),
                            ("8", "8º Ano"),
                            ("9", "9º Ano"),
                            ("1S", "1ª Série"),
                            ("2S", "2ª Série"),
                            ("3S", "3ª Série"),
                        ],
                        max_length=10,
                        verbose_name="Série",
                    ),
                ),
                ("ano_letivo", models.PositiveIntegerField(verbose_name="Ano letivo")),
                ("ativa", models.BooleanField(default=True, verbose_name="Ativa")),
                ("criado_em", models.DateTimeField(auto_now_add=True)),
                ("atualizado_em", models.DateTimeField(auto_now=True)),
                (
                    "professor_responsavel",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="turmas_responsaveis",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Professor responsável",
                    ),
                ),
            ],
            options={
                "verbose_name": "Turma",
                "verbose_name_plural": "Turmas",
                "ordering": ["-ano_letivo", "serie", "nome"],
            },
        ),
        migrations.CreateModel(
            name="Matricula",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("data_inicio", models.DateField(verbose_name="Início")),
                (
                    "data_fim",
                    models.DateField(blank=True, null=True, verbose_name="Fim"),
                ),
                ("ativa", models.BooleanField(default=True, verbose_name="Ativa")),
                (
                    "aluno",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="matriculas",
                        to="alunos.aluno",
                        verbose_name="Aluno",
                    ),
                ),
                (
                    "turma",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="matriculas",
                        to="alunos.turma",
                        verbose_name="Turma",
                    ),
                ),
            ],
            options={
                "verbose_name": "Matrícula",
                "verbose_name_plural": "Matrículas",
                "ordering": ["-data_inicio", "-id"],
            },
        ),
        migrations.AddConstraint(
            model_name="turma",
            constraint=models.UniqueConstraint(
                fields=("nome", "serie", "ano_letivo"),
                name="unique_turma_nome_serie_ano",
            ),
        ),
        migrations.AddConstraint(
            model_name="matricula",
            constraint=models.UniqueConstraint(
                condition=models.Q(("ativa", True)),
                fields=("aluno",),
                name="unique_matricula_ativa_por_aluno",
            ),
        ),
    ]
