# Generated by Django 5.2.17 on 2026-08-20 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Questao",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "numero",
                    models.PositiveIntegerField(verbose_name="Número da questão"),
                ),
                (
                    "serie",
                    models.CharField(
                        choices=[
                            ("6", "6º Ano"),
                            ("7", "7º Ano"),
                            ("8", "8º Ano"),
                            ("9", "9º Ano"),
                        ],
                        max_length=1,
                        verbose_name="Série",
                    ),
                ),
                (
                    "dificuldade",
                    models.CharField(
                        choices=[
                            ("facil", "Fácil"),
                            ("medio", "Médio"),
                            ("dificil", "Difícil"),
                        ],
                        max_length=10,
                        verbose_name="Grau de dificuldade",
                    ),
                ),
                ("enunciado", models.TextField(verbose_name="Enunciado")),
                (
                    "alternativa_a",
                    models.CharField(max_length=500, verbose_name="Alternativa A"),
                ),
                (
                    "alternativa_b",
                    models.CharField(max_length=500, verbose_name="Alternativa B"),
                ),
                (
                    "alternativa_c",
                    models.CharField(max_length=500, verbose_name="Alternativa C"),
                ),
                (
                    "alternativa_d",
                    models.CharField(max_length=500, verbose_name="Alternativa D"),
                ),
                (
                    "resposta_correta",
                    models.CharField(
                        choices=[("A", "A"), ("B", "B"), ("C", "C"), ("D", "D")],
                        max_length=1,
                        verbose_name="Resposta correta",
                    ),
                ),
                ("criado_em", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
