# Generated by Django 5.2.17 on 2026-08-20 18:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("questoes", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Aluno",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nome",
                    models.CharField(max_length=150, verbose_name="Nome do aluno"),
                ),
                (
                    "serie",
                    models.CharField(
                        choices=[
                            ("6", "6º Ano"),
                            ("7", "7º Ano"),
                            ("8", "8º Ano"),
                            ("9", "9º Ano"),
                        ],
                        max_length=1,
                        verbose_name="Série",
                    ),
                ),
                ("criado_em", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="Resultado",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "acertos",
                    models.PositiveIntegerField(default=0, verbose_name="Acertos"),
                ),
                ("erros", models.PositiveIntegerField(default=0, verbose_name="Erros")),
                (
                    "total_questoes",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Total de questões"
                    ),
                ),
                (
                    "nota",
                    models.DecimalField(
                        decimal_places=2, default=0, max_digits=5, verbose_name="Nota"
                    ),
                ),
                ("data", models.DateTimeField(auto_now_add=True, verbose_name="Data")),
                (
                    "aluno",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="resultados",
                        to="questoes.aluno",
                        verbose_name="Aluno",
                    ),
                ),
            ],
        ),
    ]
