# Generated by Django 5.2.17 on 2026-08-20 18:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("alunos", "0002_aluno_serie"),
        ("questoes", "0002_aluno_resultado"),
    ]

    operations = [
        migrations.AlterField(
            model_name="resultado",
            name="aluno",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="resultados",
                to="alunos.aluno",
                verbose_name="Aluno",
            ),
        ),
        migrations.DeleteModel(
            name="Aluno",
        ),
    ]
