# Generated by Django 5.2.17 on 2026-08-20 21:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("alunos", "0002_aluno_serie"),
        ("questoes", "0003_alter_resultado_aluno_delete_aluno"),
    ]

    operations = [
        migrations.AddField(
            model_name="resultado",
            name="tempo_segundos",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="resultado",
            name="acertos",
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name="resultado",
            name="aluno",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="resultados",
                to="alunos.aluno",
            ),
        ),
        migrations.AlterField(
            model_name="resultado",
            name="data",
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="resultado",
            name="erros",
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name="resultado",
            name="nota",
            field=models.DecimalField(decimal_places=2, max_digits=4),
        ),
        migrations.AlterField(
            model_name="resultado",
            name="total_questoes",
            field=models.IntegerField(),
        ),
    ]
