# Generated by Django 5.2.17 on 2026-08-22 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("questoes", "0004_resultado_tempo_segundos_alter_resultado_acertos_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="resultado",
            name="xp_ganho",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
