# Generated by Django 5.2.17 on 2026-08-23 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("questoes", "0005_resultado_xp_ganho"),
    ]

    operations = [
        migrations.AlterField(
            model_name="questao",
            name="serie",
            field=models.CharField(
                choices=[
                    ("5", "5º Ano"),
                    ("6", "6º Ano"),
                    ("7", "7º Ano"),
                    ("8", "8º Ano"),
                    ("9", "9º Ano"),
                    ("1S", "1ª Série"),
                    ("2S", "2ª Série"),
                    ("3S", "3ª Série"),
                ],
                max_length=2,
                verbose_name="Série",
            ),
        ),
    ]
