# Generated by Django 5.2.17 on 2026-08-23 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("questoes", "0006_alter_questao_serie"),
    ]

    operations = [
        migrations.AlterField(
            model_name="questao",
            name="numero",
            field=models.PositiveIntegerField(
                editable=False, verbose_name="Número da questão"
            ),
        ),
    ]
