# Generated by Django 5.2.17 on 2026-08-23 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("questoes", "0007_alter_questao_numero"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="questao",
            constraint=models.UniqueConstraint(
                fields=("serie", "numero"), name="unique_numero_por_serie"
            ),
        ),
    ]
