# Generated by Django 5.2.17 on 2026-08-23 18:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("questoes", "0008_questao_unique_numero_por_serie"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="questao",
            options={"ordering": ["serie", "numero"]},
        ),
    ]
