# Generated by Django 5.2.15 on 2026-09-09 01:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("questoes", "0009_alter_questao_options"),
    ]

    operations = [
        migrations.CreateModel(
            name="RespostaResultado",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "resposta",
                    models.CharField(
                        blank=True,
                        choices=[("A", "A"), ("B", "B"), ("C", "C"), ("D", "D")],
                        max_length=1,
                        null=True,
                        verbose_name="Resposta do aluno",
                    ),
                ),
                (
                    "resposta_correta",
                    models.CharField(
                        choices=[("A", "A"), ("B", "B"), ("C", "C"), ("D", "D")],
                        max_length=1,
                        verbose_name="Gabarito na prova",
                    ),
                ),
                ("correta", models.BooleanField(verbose_name="Acertou")),
                (
                    "questao",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="respostas_resultados",
                        to="questoes.questao",
                        verbose_name="Questão",
                    ),
                ),
                (
                    "resultado",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="respostas_questoes",
                        to="questoes.resultado",
                        verbose_name="Resultado",
                    ),
                ),
            ],
            options={
                "verbose_name": "Resposta do resultado",
                "verbose_name_plural": "Respostas dos resultados",
                "constraints": [
                    models.UniqueConstraint(
                        fields=("resultado", "questao"),
                        name="unique_resposta_por_questao_no_resultado",
                    )
                ],
            },
        ),
    ]
