# Generated by Django 5.2.15 on 2026-09-09 02:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("questoes", "0010_respostaresultado"),
    ]

    operations = [
        migrations.CreateModel(
            name="QuestaoVersao",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "versao",
                    models.PositiveIntegerField(verbose_name="Número da versão"),
                ),
                (
                    "numero",
                    models.PositiveIntegerField(
                        verbose_name="Número da questão na época"
                    ),
                ),
                (
                    "serie",
                    models.CharField(
                        choices=[
                            ("5", "5º Ano"),
                            ("6", "6º Ano"),
                            ("7", "7º Ano"),
                            ("8", "8º Ano"),
                            ("9", "9º Ano"),
                            ("1S", "1ª Série"),
                            ("2S", "2ª Série"),
                            ("3S", "3ª Série"),
                        ],
                        max_length=2,
                        verbose_name="Série",
                    ),
                ),
                (
                    "dificuldade",
                    models.CharField(
                        choices=[
                            ("facil", "Fácil"),
                            ("medio", "Médio"),
                            ("dificil", "Difícil"),
                        ],
                        max_length=10,
                        verbose_name="Grau de dificuldade",
                    ),
                ),
                ("enunciado", models.TextField(verbose_name="Enunciado")),
                (
                    "alternativa_a",
                    models.CharField(max_length=500, verbose_name="Alternativa A"),
                ),
                (
                    "alternativa_b",
                    models.CharField(max_length=500, verbose_name="Alternativa B"),
                ),
                (
                    "alternativa_c",
                    models.CharField(max_length=500, verbose_name="Alternativa C"),
                ),
                (
                    "alternativa_d",
                    models.CharField(max_length=500, verbose_name="Alternativa D"),
                ),
                (
                    "resposta_correta",
                    models.CharField(
                        choices=[("A", "A"), ("B", "B"), ("C", "C"), ("D", "D")],
                        max_length=1,
                        verbose_name="Resposta correta",
                    ),
                ),
                (
                    "criado_em",
                    models.DateTimeField(auto_now_add=True, verbose_name="Criada em"),
                ),
                (
                    "questao",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="versoes",
                        to="questoes.questao",
                        verbose_name="Questão",
                    ),
                ),
            ],
            options={
                "verbose_name": "Versão da questão",
                "verbose_name_plural": "Versões das questões",
                "ordering": ["questao", "versao"],
            },
        ),
        migrations.AddField(
            model_name="questao",
            name="versao_atual",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to="questoes.questaoversao",
                verbose_name="Versão atual",
            ),
        ),
        migrations.AddField(
            model_name="respostaresultado",
            name="questao_versao",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="respostas",
                to="questoes.questaoversao",
                verbose_name="Versão utilizada",
            ),
        ),
        migrations.AddConstraint(
            model_name="questaoversao",
            constraint=models.UniqueConstraint(
                fields=("questao", "versao"), name="unique_versao_por_questao"
            ),
        ),
    ]
