# Generated by Django 5.2.15 on 2026-09-09 04:34

import questoes.media
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("questoes", "0012_seed_questaoversao_inicial"),
    ]

    operations = [
        migrations.AddField(
            model_name="questao",
            name="imagem",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to=questoes.media.upload_imagem_questao,
                verbose_name="Imagem da questão",
            ),
        ),
        migrations.AddField(
            model_name="questao",
            name="imagem_alt",
            field=models.CharField(
                blank=True,
                help_text="Descrição para leitores de tela. Opcional, mas recomendado se houver imagem.",
                max_length=200,
                verbose_name="Texto alternativo da imagem",
            ),
        ),
        migrations.AddField(
            model_name="questaoversao",
            name="imagem",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to=questoes.media.upload_imagem_questao,
                verbose_name="Imagem da questão",
            ),
        ),
        migrations.AddField(
            model_name="questaoversao",
            name="imagem_alt",
            field=models.CharField(
                blank=True, max_length=200, verbose_name="Texto alternativo da imagem"
            ),
        ),
    ]
