# Generated by Django 5.2.15 on 2026-09-09 05:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("alunos", "0007_turma_matricula"),
        ("questoes", "0013_midia_imagens"),
    ]

    operations = [
        migrations.AddField(
            model_name="resultado",
            name="matricula",
            field=models.ForeignKey(
                blank=True,
                help_text="Vínculo turma–aluno vigente quando a prova foi finalizada. Nulo em tentativas anteriores às turmas.",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="resultados",
                to="alunos.matricula",
                verbose_name="Matrícula no momento da prova",
            ),
        ),
    ]
