# Generated by Django 5.2.15 on 2026-09-09 05:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("alunos", "0008_seed_turma_permissions"),
        ("questoes", "0014_turma_matricula"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Avaliacao",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("titulo", models.CharField(max_length=180)),
                ("descricao", models.TextField(blank=True)),
                (
                    "serie",
                    models.CharField(
                        choices=[
                            ("5", "5º Ano"),
                            ("6", "6º Ano"),
                            ("7", "7º Ano"),
                            ("8", "8º Ano"),
                            ("9", "9º Ano"),
                            ("1S", "1ª Série"),
                            ("2S", "2ª Série"),
                            ("3S", "3ª Série"),
                        ],
                        max_length=10,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("rascunho", "Rascunho"),
                            ("publicada", "Publicada"),
                            ("encerrada", "Encerrada"),
                        ],
                        default="rascunho",
                        max_length=12,
                    ),
                ),
                ("data_inicio", models.DateTimeField(blank=True, null=True)),
                ("data_fim", models.DateTimeField(blank=True, null=True)),
                (
                    "tempo_limite_minutos",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="Vazio = sem limite. Validado no servidor.",
                        null=True,
                        verbose_name="Tempo limite (minutos)",
                    ),
                ),
                ("tentativas_maximas", models.PositiveIntegerField(default=1)),
                ("publicado_em", models.DateTimeField(blank=True, null=True)),
                ("criado_em", models.DateTimeField(auto_now_add=True)),
                ("atualizado_em", models.DateTimeField(auto_now=True)),
                (
                    "criado_por",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="avaliacoes_criadas",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "turma",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="avaliacoes",
                        to="alunos.turma",
                    ),
                ),
            ],
            options={
                "verbose_name": "Avaliação",
                "verbose_name_plural": "Avaliações",
                "ordering": ["-criado_em"],
                "permissions": [
                    ("view_relatorio_pedagogico", "Pode ver relatórios pedagógicos")
                ],
            },
        ),
        migrations.AddField(
            model_name="resultado",
            name="avaliacao",
            field=models.ForeignKey(
                blank=True,
                help_text="Nulo no simulado livre por série.",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="resultados",
                to="questoes.avaliacao",
                verbose_name="Avaliação",
            ),
        ),
        migrations.CreateModel(
            name="AvaliacaoQuestao",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ordem", models.PositiveIntegerField(default=1)),
                (
                    "avaliacao",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="itens",
                        to="questoes.avaliacao",
                    ),
                ),
                (
                    "questao",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="itens_avaliacao",
                        to="questoes.questao",
                    ),
                ),
                (
                    "questao_versao",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="itens_avaliacao",
                        to="questoes.questaoversao",
                        verbose_name="Versão congelada",
                    ),
                ),
            ],
            options={
                "verbose_name": "Questão da avaliação",
                "ordering": ["ordem", "id"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("avaliacao", "questao"),
                        name="unique_questao_por_avaliacao",
                    )
                ],
            },
        ),
    ]
