# Generated by Django 5.2.15 on 2026-09-08 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_profile"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="profile",
            options={
                "permissions": [
                    ("access_area_aluno", "Pode acessar a área do aluno"),
                    ("access_area_professor", "Pode acessar a área do professor"),
                    ("access_area_coordenacao", "Pode acessar a área da coordenação"),
                    ("access_area_direcao", "Pode acessar a área da direção"),
                ],
                "verbose_name": "Perfil",
                "verbose_name_plural": "Perfis",
            },
        ),
        migrations.AlterField(
            model_name="profile",
            name="role",
            field=models.CharField(
                blank=True,
                choices=[
                    ("aluno", "Aluno"),
                    ("professor", "Professor"),
                    ("coordenador", "Coordenador"),
                    ("diretor", "Diretor"),
                ],
                default="",
                help_text="Campo complementar. O acesso ao sistema é definido por grupos e permissões Django.",
                max_length=20,
                verbose_name="Perfil (informativo)",
            ),
        ),
    ]
